version: "2"
services:
  backend:
    build: './backend'
    volumes:
      - './backend:/app'
    ports:
      - "3030:3030"
    depends_on:
      - mongodb

  frontend:
    build: './frontend'
    volumes:
      - './frontend:/app'
    ports:
      - "8080:8080"
    depends_on:
      - backend

  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  mongodb:
    restart: always
    container_name: mongodb
    volumes:
      - ./mongo/data:/data/db
    image: mongo
    ports:
      - "27017:27017"